#' @include yakf-package.R
#' @exportClass DlmSamples
NULL

#' DLM Samples class
#'
#' Samples of observations and states generated from a DLM.
#' These objects are usually generated by \code{\link{dlm_recursion}}.
#'
#' @section Slots:
#' \describe{
#' \item{\code{a}}{\code{matrix} containing the latent states}
#' \item{\code{y}}{\code{matrix} containing the observations}
#' }
#'
#' @docType class
#' @seealso \code{\link{dlm_recursion}} which returns object of this class.
DlmSamples <-
  setClass("DlmSamples",
           representation =
           representation(a = "matrix", y = "matrix"))

validity.DlmSamples <- function(object) {
  for (i in c("a", "y")) {
    if (mode(slot(object, i)) != "numeric") {
      return(sprintf("Slot %s does not contain numeric data", i))
    }
  }
  if (nrow(object@a) != (nrow(object@y) + 1)) {
    return("nrow(object@a) != nrow(object@y) + 1")
  }
  TRUE
}

setValidity("DlmSamples", validity.DlmSamples)
