#' @include yakf-package.R
#' @exportClass DlmSamples
NULL

#' DLM Samples class
#'
#' Samples of observations and states generated from a DLM.
#' These objects are usually generated by \code{\link{dlm_recursion}}.
#'
#' The function \code{DlmSamples} is a generator function for
#' objects of this class.
#'
#' @param ... Data to include in the new object.
#' 
#' @section Slots:
#' \describe{
#' \item{\code{a}}{\code{Matrix} containing the latent states}
#' \item{\code{y}}{\code{Matrix} containing the observations}
#' }
#'
#' @docType class
#' @seealso \code{\link{dlm_recursion}} which returns object of this class.
DlmSamples <-
  setClass("DlmSamples",
           representation =
           representation(a = "Matrix", y = "Matrix"))

validity.DlmSamples <- function(object) {
  if (ncol(object@a) != (ncol(object@y) + 1)) {
    return("ncol(object@a) != ncol(object@y) + 1")
  }
  TRUE
}

setValidity("DlmSamples", validity.DlmSamples)
